17 error Error: Command failed with exit code 1: git remote update
17 error error: cannot lock ref 'refs/remotes/origin/main': is at e3f6438a614c1ae9aa0929330b0de420a121c7ee but expected e2e4b61b82d6bd8c266747f0483368e3341bbc07
17 error From https://github.com/grngxd/silica
17 error  ! e2e4b61..e3f6438  main       -> origin/main  (unable to update local ref)
17 error     at makeError (E:\Apps\silica\node_modules\.pnpm\execa@5.0.0\node_modules\execa\lib\error.js:59:11)
17 error     at module.exports.sync (E:\Apps\silica\node_modules\.pnpm\execa@5.0.0\node_modules\execa\index.js:186:17)
17 error     at Object.execSync (E:\Apps\silica\node_modules\.pnpm\lerna@8.1.9_encoding@0.1.13\node_modules\lerna\dist\index.js:1579:31)
17 error     at updateRemote (E:\Apps\silica\node_modules\.pnpm\lerna@8.1.9_encoding@0.1.13\node_modules\lerna\dist\index.js:9202:18)
17 error     at isBehindUpstream (E:\Apps\silica\node_modules\.pnpm\lerna@8.1.9_encoding@0.1.13\node_modules\lerna\dist\index.js:9192:3)
17 error     at VersionCommand.initialize (E:\Apps\silica\node_modules\.pnpm\lerna@8.1.9_encoding@0.1.13\node_modules\lerna\dist\index.js:9486:57)
17 error     at VersionCommand.runCommand (E:\Apps\silica\node_modules\.pnpm\lerna@8.1.9_encoding@0.1.13\node_modules\lerna\dist\index.js:3296:36)
